Checks for xaptools.lib before continuing.

diff --git a/releases/4.1/lscores b/releases/4.1/lscores
--- a/releases/4.1/lscores
+++ b/releases/4.1/lscores
@@ -15,7 +15,12 @@
 setup()
 {
 	SCRIPTDIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
-	source "$SCRIPTDIR/xaptools.lib" 
+	if [[ -e "$SCRIPTDIR/xaptools.lib" ]] ;then
+		source "$SCRIPTDIR/xaptools.lib" 
+	else
+		echo "Unable to load xaptools.lib"
+		exit 1
+	fi
 	setcolors	
 	DEFSPACE="5"
 	MINSPACE="$DEFSPACE"
diff --git a/releases/4.1/lshosts b/releases/4.1/lshosts
--- a/releases/4.1/lshosts
+++ b/releases/4.1/lshosts
@@ -32,8 +32,12 @@
 setup()
 {
 	SCRIPTDIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
-	source "$SCRIPTDIR/xaptools.lib" 
-	setcolors
+	if [[ -e "$SCRIPTDIR/xaptools.lib" ]] ;then
+		source "$SCRIPTDIR/xaptools.lib" 
+	else
+		echo "Unable to load xaptools.lib"
+		exit 1
+	fi	setcolors
 	VERSION="0.9.7"
 	DEFSPACE="5"
 	MINSPACE="$DEFSPACE"
